### ISSUE TITLE
The visualization is terrible

### ISSUE THREAD

**Issue by vipcxj** [JinluZhang1126/MixSTE#30]
![output](https://user-images.githubusercontent.com/9250084/208347460-2793344d-1c56-4065-a015-2c5299b4ae00.gif)
Is this effect normal?
```bash
python run.py -k cpn_ft_h36m_dbb -c checkpoint --evaluate pretrained_h36m_cpn.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-video "/root/datasets/human3.6m/S11/Videos/Walking.54138969.mp4" --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60
```
This is the command.

**Comment by PrAYtele** [comment]
Same problem,It's normal,because the model's output is just gt+noise
            anim_output = {'Reconstruction': ground_truth + np.random.normal(loc=0.0, scale=0.1, size=[ground_truth.shape[0], 17, 3])}

**Comment by JinluZhang1126** [comment]
I have repaired this issue, please check again.

**Comment by 2455DD** [comment]
> I have repaired this issue, please check again.

new error occurs.
> (torch181) <username>@<hostname>:~/repo/MixSTE$ python run.py -k cpn_ft_h36m_dbb -c checkpoint --evaluate best_epoch.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0  --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60
Evaluate!
python run.py -k cpn_ft_h36m_dbb -c checkpoint --evaluate best_epoch.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60
CUDA Device Count:  1
Namespace(actions='*', alpha=0.01, batch_size=1024, beta=2, bone_length_term=True, by_subject=False, checkpoint='checkpoint', checkpoint_frequency=20, compare=False, coverlr=False, cs=512, data_augmentation=True, dataset='h36m', dense=False, dep=8, depth=4, disable_optimizations=False, downsample=1, dropout=0.0, epochs=120, evaluate='best_epoch.bin', export_training_curves=False, ft=False, ftchk='epoch_330.pth', ftpath='checkpoint/exp13_ft2d', ftpostrf=False, gpu='0', keypoints='cpn_ft_h36m_dbb', learning_rate=4e-05, linear_channel_size=1024, linear_projection=False, log='log/default', lr_decay=0.99, lr_decay_gap=10000, min_loss=100000, no_eval=False, no_proj=False, nolog=False, number_of_frames=243, postrf=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='Walking', viz_bitrate=3000, viz_camera=0, viz_downsample=2, viz_export=None, viz_limit=60, viz_no_ground_truth=False, viz_output='output.gif', viz_size=3, viz_skip=0, viz_subject='S11', viz_video=None, warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Trainable parameter count: 33.783811 Million
Loading checkpoint checkpoint/best_epoch.bin
This model was trained for 157 epochs
INFO: Testing on 225676 frames
Rendering...
Loading evaluate checkpoint checkpoint/best_epoch.bin
This model was trained for 157 epochs
MovieWriter imagemagick unavailable; trying to use pillow instead.
Traceback (most recent call last):
  File "run.py", line 876, in <module>
    input_video_skip=args.viz_skip)
  File "/home/<username>/repo/MixSTE/common/visualization.py", line 244, in render_animation
    anim.save(output, dpi=80, writer='imagemagick')
  File "/home/<username>/anaconda3/envs/torch181/lib/python3.6/site-packages/matplotlib/animation.py", line 1111, in save
    extra_args=extra_args, metadata=metadata)
TypeError: 'str' object is not callable

**Comment by wenwen12321** [comment]
> ![output](https://user-images.githubusercontent.com/9250084/208347460-2793344d-1c56-4065-a015-2c5299b4ae00.gif) [ ![output](https://user-images.githubusercontent.com/9250084/208347460-2793344d-1c56-4065-a015-2c5299b4ae00.gif) ](https://user-images.githubusercontent.com/9250084/208347460-2793344d-1c56-4065-a015-2c5299b4ae00.gif) [ ](https://user-images.githubusercontent.com/9250084/208347460-2793344d-1c56-4065-a015-2c5299b4ae00.gif) Is this effect normal?
> 
> ```shell
> python run.py -k cpn_ft_h36m_dbb -c checkpoint --evaluate pretrained_h36m_cpn.bin --render --viz-subject S11 --viz-action Walking --viz-camera 0 --viz-video "/root/datasets/human3.6m/S11/Videos/Walking.54138969.mp4" --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60
> ```
> 
> This is the command.

@JinluZhang1126 
Hi author, 

I can only output about a two-second .gif file the same as this result.
How could I output a longer .gif file as your Github main page result??

**Comment by sumonky** [comment]
Same problem,It's normal,

**Comment by jianlai123-123** [comment]
Hello, may I ask if you have successfully obtained longer outputs? If so, could you please share how you resolved it? Looking forward to your reply. Thank you. @wenwen12321
